services:
  angular-dev:
    image: node:20-alpine
    container_name: angular-dev
    working_dir: /app
    volumes:
      - ./:/app
      - /app/node_modules
    ports:
      - "4200:4200"
    command: sh -c "npm install -g @angular/cli && npm install && ng serve --host 0.0.0.0 --poll 2000"
